<?php
$title = "Dodaj novog studenta";
$this->headtitle($title);
$courses = $model->kursevi;
?>

<h3><?php echo $this->escapehtml($title) ?></h3>

<?php 

    $ime = $form->get('ime');
    $ime->setAttribute('class', 'form-control');
    $ime->setAttribute('placeholder', 'Ime ...');
    
    $prezime = $form->get('prezime');
    $prezime->setAttribute('class', 'form-control');
    $prezime->setAttribute('placeholder', 'Prezime ...');
    
    $broj_indeksa = $form->get('broj_indeksa');
    $broj_indeksa->setAttribute('class', 'form-control');
    $broj_indeksa->setAttribute('placeholder', 'Broj indeksa ...');
    
    $email = $form->get('email');
    $email->setAttribute('class', 'form-control');
    $email->setAttribute('placeholder', 'Email ...');
    
    $image = $form->get('image');
    $image->setAttribute('class', 'form-control');
    $image->setAttribute('id', 'imgUpload');
    
    $submit = $form->get('submit');
    $submit->setAttribute('class', 'btn btn-primary');
    
    if(isset($id))
        $form->setAttribute('action', $this->url('studenti', ['action' => 'editWithModel', 'id' => $id]));
    else 
        $form->setAttribute('action', $this->url('studenti', ['action' => 'addWithModel']));
    
    $form->prepare();
    
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
?>

<div id="tabs">
	<ul>
		<li><a href="#tab1">Licni podaci</a></li>
		<li><a href="#tab2">Upisani kursevi</a></li>
	</ul>
	<div id="tab1">
    	<div class='form-group'>
            <?php echo $this->formLabel($ime) ?>
            <div class='col-xs-4'>
                <?php echo $this->formElement($ime);?>
                <?php echo $this->formElementErrors()->render($ime, ['class' => 'help-block']) ?>
            </div>
        </div>
        
        <div class='form-group'>
            <?php echo $this->formLabel($prezime) ?>
            <div class='col-xs-4'>
                <?php echo $this->formElement($prezime);?>
                <?php echo $this->formElementErrors()->render($prezime, ['class' => 'help-block']) ?>
            </div>
        </div>
        
        <div class='form-group'>
            <?php echo $this->formLabel($broj_indeksa) ?>
            <div class='col-xs-4'>
                <?php echo $this->formElement($broj_indeksa);?>
                <?php echo $this->formElementErrors()->render($broj_indeksa, ['class' => 'help-block']) ?>
            </div>
        </div>
        
        <div class='form-group'>
            <?php echo $this->formLabel($email) ?>
            <div class='col-xs-4'>
                <?php echo $this->formElement($email);?>
                <?php echo $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
            </div>
        </div>
        
        <div class='form-group'>
            <?php echo $this->formLabel($image) ?>
            <div class='col-xs-4'>
                <?php echo $this->formElement($image);?>
                <?php echo $this->formElementErrors()->render($image, ['class' => 'help-block']) ?>
            </div>
        </div>
        
        <div class='form-group'>
            <div class="col-xs-2 control-label"></div>
            <div class='col-xs-4'>
            <?php if(isset($photo) && $photo != ""):?>
                <img id="imageupload" src="<?php echo $photo ?>" alt="uploaded image preview" width="100%" height="auto" />
            <?php else: ?>
            	<img id="imageupload" alt="uploaded image preview" width="100%" height="auto" />
            <?php endif; ?>
            </div>
        </div>
	</div>
	<div id="tab2">
		<?php if(count($courses) > 0): ?>
			<table class="table">
				<thead>
					<tr>
						<th>Predmet</th>
						<th>Predmetni profesor</th>
						<th>Akcija</th>
					</tr>
				</thead>
				<tbody>
			    <?php foreach($courses as $course): ?>
					<tr>
						<td><?php echo $course->imePredmeta ?></td>
						<td><?php echo $course->imeProfesora ?></td>
					</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
		<?php else:?>
			<p>Trenutno nema predmeta na kojima je student upisan.</p>
		<?php endif; ?>
		<a href="<?= $this->url("studenti", ["action" => "addCourse", "id" => $id]) ?>" class="btn btn-default">Dodati novi predmet</a>
	</div>
</div>

<?php 
    echo $this->formSubmit($submit);
?>
<a href="<?php echo $this->url('studenti')?>" class="btn btn-default" style="margin-left: 20px">Nazad</a>
<?php 
    echo $this->form()->closeTag();    
?>

<script>
$(function() {	
	$('#imgUpload').change(function(evt) {
		console.log('changed');

		if($('input#imgUpload')[0].files[0]) {
			var filerdr = new FileReader();
			filerdr.onload = function(e) {
		        $('#imageupload').attr('src', e.target.result);
			}
			
		    filerdr.readAsDataURL($('input#imgUpload')[0].files[0]);		        
		}
	});	
});

$(document).ready(function() {
	$('#tabs').tabs();
});

</script>